# Instance tag type and dimensional enums


type ChargingPort_InstanceTag @instanceTag @vspec(element: BRANCH, fqn: "Vehicle.Powertrain.TractionBattery.Charging.ChargingPort") {
  dimension1: ChargingPort_InstanceTag_Dimension1
}

"""Dimensional enum for VSS instance dimension 1."""
enum ChargingPort_InstanceTag_Dimension1 {
  FRONT_LEFT @vspec(originalName: "FrontLeft")
  FRONT_MIDDLE @vspec(originalName: "FrontMiddle")
  FRONT_RIGHT @vspec(originalName: "FrontRight")
  REAR_LEFT @vspec(originalName: "RearLeft")
  REAR_MIDDLE @vspec(originalName: "RearMiddle")
  REAR_RIGHT @vspec(originalName: "RearRight")
  ANY_POSITION @vspec(originalName: "AnyPosition")
}

extend type ChargingPort {
  instanceTag: ChargingPort_InstanceTag
}