# Instance tag type and dimensional enums


type ChargingPort_InstanceTag @instanceTag @vspec(element: BRANCH, fqn: "Vehicle.Powertrain.TractionBattery.Charging.ChargingPort", metadata: [{key: "instances", value: "[['FrontLeft', 'FrontMiddle', 'FrontRight', 'RearLeft', 'RearMiddle', 'RearRight', 'AnyPosition']]"}]) {
  dimension1: ChargingPort_InstanceTag_Dimension1
}

"""Dimensional enum for VSS instance dimension 1."""
enum ChargingPort_InstanceTag_Dimension1 {
  FRONT_LEFT @vspec(metadata: [{key: "originalName", value: "FrontLeft"}])
  FRONT_MIDDLE @vspec(metadata: [{key: "originalName", value: "FrontMiddle"}])
  FRONT_RIGHT @vspec(metadata: [{key: "originalName", value: "FrontRight"}])
  REAR_LEFT @vspec(metadata: [{key: "originalName", value: "RearLeft"}])
  REAR_MIDDLE @vspec(metadata: [{key: "originalName", value: "RearMiddle"}])
  REAR_RIGHT @vspec(metadata: [{key: "originalName", value: "RearRight"}])
  ANY_POSITION @vspec(metadata: [{key: "originalName", value: "AnyPosition"}])
}

extend type ChargingPort {
  instanceTag: ChargingPort_InstanceTag
}