# Instance tag type and dimensional enums

type ControlUnit_InstanceTag @instanceTag @vspec(element: BRANCH, fqn: "Vehicle.ControlUnit") {
  dimension1: ControlUnit_InstanceTag_Dimension1
}

"""
Dimensional enum for VSS instance dimension 1.
"""
enum ControlUnit_InstanceTag_Dimension1 {
  CENTRAL @vspec(originalName: "Central")
  FRONT_LEFT @vspec(originalName: "FrontLeft")
  FRONT_RIGHT @vspec(originalName: "FrontRight")
  REAR_LEFT1 @vspec(originalName: "RearLeft1")
  REAR_LEFT2 @vspec(originalName: "RearLeft2")
  TRUNK @vspec(originalName: "Trunk")
}

extend type ControlUnit {
  instanceTag: ControlUnit_InstanceTag
}
