# Instance tag type and dimensional enums


type DirectionIndicator_InstanceTag @instanceTag @vspec(element: BRANCH, fqn: "Vehicle.Body.Lights.DirectionIndicator", metadata: [{key: "instances", value: "['Left', 'Right']"}]) {
  dimension1: DirectionIndicator_InstanceTag_Dimension1
}

"""Dimensional enum for VSS instance dimension 1."""
enum DirectionIndicator_InstanceTag_Dimension1 {
  LEFT @vspec(metadata: [{key: "originalName", value: "Left"}])
  RIGHT @vspec(metadata: [{key: "originalName", value: "Right"}])
}

extend type DirectionIndicator {
  instanceTag: DirectionIndicator_InstanceTag
}