# Instance tag type and dimensional enums


type Door_InstanceTag @instanceTag @vspec(element: BRANCH, fqn: "Vehicle.Cabin.Door", metadata: [{key: "instances", value: "['Row[1,2]', ['DriverSide', 'PassengerSide']]"}]) {
  dimension1: Door_InstanceTag_Dimension1
  dimension2: Door_InstanceTag_Dimension2
}

"""Dimensional enum for VSS instance dimension 1."""
enum Door_InstanceTag_Dimension1 {
  ROW1 @vspec(metadata: [{key: "originalName", value: "Row1"}])
  ROW2 @vspec(metadata: [{key: "originalName", value: "Row2"}])
}

"""Dimensional enum for VSS instance dimension 2."""
enum Door_InstanceTag_Dimension2 {
  DRIVER_SIDE @vspec(metadata: [{key: "originalName", value: "DriverSide"}])
  PASSENGER_SIDE @vspec(metadata: [{key: "originalName", value: "PassengerSide"}])
}

extend type Door {
  instanceTag: Door_InstanceTag
}