# Instance tag type and dimensional enums

type Seat_InstanceTag @instanceTag @vspec(element: BRANCH, fqn: "Vehicle.Cabin.Seat") {
  dimension1: Seat_InstanceTag_Dimension1
  dimension2: Seat_InstanceTag_Dimension2
}

"""
Dimensional enum for VSS instance dimension 1.
"""
enum Seat_InstanceTag_Dimension1 {
  ROW1 @vspec(originalName: "Row1")
  ROW2 @vspec(originalName: "Row2")
}

"""
Dimensional enum for VSS instance dimension 2.
"""
enum Seat_InstanceTag_Dimension2 {
  DRIVER_SIDE @vspec(originalName: "DriverSide")
  MIDDLE @vspec(originalName: "Middle")
  PASSENGER_SIDE @vspec(originalName: "PassengerSide")
}

extend type Seat {
  instanceTag: Seat_InstanceTag
}
