# Instance tag type and dimensional enums

type Spotlight_InstanceTag
  @instanceTag
  @vspec(element: BRANCH, fqn: "Vehicle.Cabin.Light.Spotlight") {
  dimension1: Spotlight_InstanceTag_Dimension1
  dimension2: Spotlight_InstanceTag_Dimension2
}

"""
Dimensional enum for VSS instance dimension 1.
"""
enum Spotlight_InstanceTag_Dimension1 {
  ROW1 @vspec(originalName: "Row1")
  ROW2 @vspec(originalName: "Row2")
  ROW3 @vspec(originalName: "Row3")
  ROW4 @vspec(originalName: "Row4")
}

"""
Dimensional enum for VSS instance dimension 2.
"""
enum Spotlight_InstanceTag_Dimension2 {
  DRIVER_SIDE @vspec(originalName: "DriverSide")
  PASSENGER_SIDE @vspec(originalName: "PassengerSide")
}

extend type Spotlight {
  instanceTag: Spotlight_InstanceTag
}
