# Instance tag type and dimensional enums


type Suspension_Axle_Wheel_InstanceTag @instanceTag @vspec(element: BRANCH, fqn: "Vehicle.MotionManagement.Suspension.Axle.Wheel") {
  dimension1: Suspension_Axle_Wheel_InstanceTag_Dimension1
}

"""Dimensional enum for VSS instance dimension 1."""
enum Suspension_Axle_Wheel_InstanceTag_Dimension1 {
  LEFT @vspec(originalName: "Left")
  RIGHT @vspec(originalName: "Right")
}

extend type Suspension_Axle_Wheel {
  instanceTag: Suspension_Axle_Wheel_InstanceTag
}