# Domain-specific GraphQL types


"""
Units for "length"
"""
enum LengthUnitEnum @vspec(element: QUANTITY_KIND) {
  MILLIMETER @vspec(element: UNIT)
  CENTIMETER @vspec(element: UNIT)
  METER @vspec(element: UNIT)
  KILOMETER @vspec(element: UNIT)
  INCH @vspec(element: UNIT)
}

"""
Units for "velocity"
"""
enum VelocityUnitEnum @vspec(element: QUANTITY_KIND) {
  KILOMETER_PER_HOUR @vspec(element: UNIT)
  METERS_PER_SECOND @vspec(element: UNIT)
}

"""
Units for "acceleration"
"""
enum AccelerationUnitEnum @vspec(element: QUANTITY_KIND) {
  METERS_PER_SECOND_SQUARED @vspec(element: UNIT)
  CENTIMETERS_PER_SECOND_SQUARED @vspec(element: UNIT)
}

"""
Units for "volume"
"""
enum VolumeUnitEnum @vspec(element: QUANTITY_KIND) {
  MILLILITER @vspec(element: UNIT)
  LITER @vspec(element: UNIT)
  CUBIC_CENTIMETERS @vspec(element: UNIT)
}

"""
Units for "temperature"
"""
enum TemperatureUnitEnum @vspec(element: QUANTITY_KIND) {
  DEGREE_CELSIUS @vspec(element: UNIT)
  DEGREE_FAHRENHEIT @vspec(element: UNIT)
}

"""
Units for "angle"
"""
enum AngleUnitEnum @vspec(element: QUANTITY_KIND) {
  DEGREE @vspec(element: UNIT)
}

"""
Units for "angular-speed"
"""
enum AngularSpeedUnitEnum @vspec(element: QUANTITY_KIND) {
  DEGREE_PER_SECOND @vspec(element: UNIT)
  RADIANS_PER_SECOND @vspec(element: UNIT)
}

"""
Units for "power"
"""
enum PowerUnitEnum @vspec(element: QUANTITY_KIND) {
  WATT @vspec(element: UNIT)
  KILOWATT @vspec(element: UNIT)
  HORSEPOWER @vspec(element: UNIT)
}

"""
Units for "work"
"""
enum WorkUnitEnum @vspec(element: QUANTITY_KIND) {
  KILOWATT_HOURS @vspec(element: UNIT)
}

"""
Units for "mass"
"""
enum MassUnitEnum @vspec(element: QUANTITY_KIND) {
  GRAM @vspec(element: UNIT)
  KILOGRAM @vspec(element: UNIT)
  POUND @vspec(element: UNIT)
}

"""
Units for "voltage"
"""
enum VoltageUnitEnum @vspec(element: QUANTITY_KIND) {
  VOLT @vspec(element: UNIT)
}

"""
Units for "electric-current"
"""
enum ElectricCurrentUnitEnum @vspec(element: QUANTITY_KIND) {
  AMPERE @vspec(element: UNIT)
}

"""
Units for "electric-charge"
"""
enum ElectricChargeUnitEnum @vspec(element: QUANTITY_KIND) {
  AMPERE_HOURS @vspec(element: UNIT)
}

"""
Units for "duration"
"""
enum DurationUnitEnum @vspec(element: QUANTITY_KIND) {
  NANOSECOND @vspec(element: UNIT)
  MILLISECOND @vspec(element: UNIT)
  SECOND @vspec(element: UNIT)
  MINUTE @vspec(element: UNIT)
  HOUR @vspec(element: UNIT)
  DAYS @vspec(element: UNIT)
  WEEKS @vspec(element: UNIT)
  MONTHS @vspec(element: UNIT)
  YEARS @vspec(element: UNIT)
}

"""
Units for "datetime"
"""
enum DatetimeUnitEnum @vspec(element: QUANTITY_KIND) {
  U_N_I_X_TIMESTAMP @vspec(element: UNIT)
  ISO_8601 @vspec(element: UNIT)
}

"""
Units for "pressure"
"""
enum PressureUnitEnum @vspec(element: QUANTITY_KIND) {
  MILLIBAR @vspec(element: UNIT)
  PASCAL @vspec(element: UNIT)
  KILOPASCAL @vspec(element: UNIT)
  POUNDS_PER_SQUARE_INCH @vspec(element: UNIT)
}

"""
Units for "rating"
"""
enum RatingUnitEnum @vspec(element: QUANTITY_KIND) {
  STARS @vspec(element: UNIT)
}

"""
Units for "mass-per-time"
"""
enum MassPerTimeUnitEnum @vspec(element: QUANTITY_KIND) {
  GRAMS_PER_SECOND @vspec(element: UNIT)
}

"""
Units for "mass-per-distance"
"""
enum MassPerDistanceUnitEnum @vspec(element: QUANTITY_KIND) {
  GRAMS_PER_KILOMETER @vspec(element: UNIT)
}

"""
Units for "energy-consumption-per-distance"
"""
enum EnergyConsumptionPerDistanceUnitEnum @vspec(element: QUANTITY_KIND) {
  KILOWATT_HOURS_PER_100_KILOMETERS @vspec(element: UNIT)
  WATT_HOUR_PER_KM @vspec(element: UNIT)
}

"""
Units for "volume-per-distance"
"""
enum VolumePerDistanceUnitEnum @vspec(element: QUANTITY_KIND) {
  MILLILITER_PER_100_KILOMETERS @vspec(element: UNIT)
  LITER_PER_100_KILOMETERS @vspec(element: UNIT)
}

"""
Units for "volume-flow-rate"
"""
enum VolumeFlowRateUnitEnum @vspec(element: QUANTITY_KIND) {
  LITER_PER_HOUR @vspec(element: UNIT)
}

"""
Units for "distance-per-volume"
"""
enum DistancePerVolumeUnitEnum @vspec(element: QUANTITY_KIND) {
  MILES_PER_US_GALLON @vspec(element: UNIT)
  MILES_PER_IMPERIAL_GALLON @vspec(element: UNIT)
  MILES_PER_US_GALLON_EQUIVALENT @vspec(element: UNIT)
  MILES_PER_US_GALLON_DEPRECATED @vspec(element: UNIT)
  KILOMETERS_PER_LITER @vspec(element: UNIT)
}

"""
Units for "force"
"""
enum ForceUnitEnum @vspec(element: QUANTITY_KIND) {
  NEWTON @vspec(element: UNIT)
  KILO_NEWTON @vspec(element: UNIT)
}

"""
Units for "torque"
"""
enum TorqueUnitEnum @vspec(element: QUANTITY_KIND) {
  NEWTON_METER @vspec(element: UNIT)
}

"""
Units for "rotational-speed"
"""
enum RotationalSpeedUnitEnum @vspec(element: QUANTITY_KIND) {
  REVOLUTIONS_PER_MINUTE @vspec(element: UNIT)
}

"""
Units for "frequency"
"""
enum FrequencyUnitEnum @vspec(element: QUANTITY_KIND) {
  HERTZ @vspec(element: UNIT)
  CYCLES_PER_MINUTE @vspec(element: UNIT)
  BEATS_PER_MINUTE @vspec(element: UNIT)
}

"""
Units for "relation"
"""
enum RelationUnitEnum @vspec(element: QUANTITY_KIND) {
  RATIO @vspec(element: UNIT)
  PERCENT @vspec(element: UNIT)
  NANO_METER_PER_KILOMETER @vspec(element: UNIT)
  DECIBEL_MILLIWATT @vspec(element: UNIT)
  DECIBEL @vspec(element: UNIT)
}

"""
Units for "resistance"
"""
enum ResistanceUnitEnum @vspec(element: QUANTITY_KIND) {
  OHM @vspec(element: UNIT)
}

"""
Units for "illuminance"
"""
enum IlluminanceUnitEnum @vspec(element: QUANTITY_KIND) {
  LUX @vspec(element: UNIT)
}