# Domain-specific GraphQL types

"""
Antilock Braking System signals.
"""
type ABS @vspec(element: BRANCH, fqn: "Vehicle.ADAS.ABS") {
  """
  Indicates if ABS is enabled. True = Enabled. False = Disabled.
  """
  isEnabled: Boolean @vspec(element: ACTUATOR, fqn: "Vehicle.ADAS.ABS.IsEnabled")

  """
  Indicates if ABS is currently regulating brake pressure. True = Engaged. False = Not Engaged.
  """
  isEngaged: Boolean @vspec(element: SENSOR, fqn: "Vehicle.ADAS.ABS.IsEngaged")

  """
  Indicates if ABS incurred an error condition. True = Error. False = No Error.
  """
  isError: Boolean @vspec(element: SENSOR, fqn: "Vehicle.ADAS.ABS.IsError")
}
