# Domain-specific GraphQL types


"""Voltage information for cells in the battery pack."""
type CellVoltage @vspec(element: BRANCH, fqn: "Vehicle.Powertrain.TractionBattery.CellVoltage") {
  """
  Array of cell voltages. Length or array shall correspond to number of cells in vehicle.
  """
  cellVoltages: [Float!] @vspec(element: SENSOR, fqn: "Vehicle.Powertrain.TractionBattery.CellVoltage.CellVoltages")

  """Identifier of the battery cell with highest voltage."""
  idMax: UInt16 @vspec(element: SENSOR, fqn: "Vehicle.Powertrain.TractionBattery.CellVoltage.IdMax")

  """Identifier of the battery cell with lowest voltage."""
  idMin: UInt16 @vspec(element: SENSOR, fqn: "Vehicle.Powertrain.TractionBattery.CellVoltage.IdMin")

  """Current voltage of the battery cell with highest voltage."""
  max(unit: VoltageUnitEnum = VOLT): Float @vspec(element: SENSOR, fqn: "Vehicle.Powertrain.TractionBattery.CellVoltage.Max")

  """Current voltage of the battery cell with lowest voltage."""
  min(unit: VoltageUnitEnum = VOLT): Float @vspec(element: SENSOR, fqn: "Vehicle.Powertrain.TractionBattery.CellVoltage.Min")
}