# Domain-specific GraphQL types


"""Current charging current."""
type ChargeCurrent @vspec(element: BRANCH, fqn: "Vehicle.Powertrain.TractionBattery.Charging.ChargeCurrent") {
  """
  Current DC charging current at inlet. Negative if returning energy to grid.
  """
  dc(unit: ElectricCurrentUnitEnum = AMPERE): Float @vspec(element: SENSOR, fqn: "Vehicle.Powertrain.TractionBattery.Charging.ChargeCurrent.DC")

  """
  Current AC charging current (rms) at inlet for Phase 1. Negative if returning energy to grid.
  """
  phase1(unit: ElectricCurrentUnitEnum = AMPERE): Float @vspec(element: SENSOR, fqn: "Vehicle.Powertrain.TractionBattery.Charging.ChargeCurrent.Phase1")

  """
  Current AC charging current (rms) at inlet for Phase 2. Negative if returning energy to grid.
  """
  phase2(unit: ElectricCurrentUnitEnum = AMPERE): Float @vspec(element: SENSOR, fqn: "Vehicle.Powertrain.TractionBattery.Charging.ChargeCurrent.Phase2")

  """
  Current AC charging current (rms) at inlet for Phase 3. Negative if returning energy to grid.
  """
  phase3(unit: ElectricCurrentUnitEnum = AMPERE): Float @vspec(element: SENSOR, fqn: "Vehicle.Powertrain.TractionBattery.Charging.ChargeCurrent.Phase3")
}