# Domain-specific GraphQL types


"""All data concerning steering, suspension, wheels, and brakes."""
type Chassis @vspec(element: BRANCH, fqn: "Vehicle.Chassis") {
  """Number of axles on the vehicle"""
  axleCount: UInt8 @vspec(element: ATTRIBUTE, fqn: "Vehicle.Chassis.AxleCount")

  """Overall wheelbase, in mm."""
  wheelbase(unit: LengthUnitEnum = MILLIMETER): UInt16 @vspec(element: ATTRIBUTE, fqn: "Vehicle.Chassis.Wheelbase")
  accelerator: Accelerator
  axles: [Chassis_Axle]
  brake: Chassis_Brake
  parkingBrake: ParkingBrake
  steeringWheel: Chassis_SteeringWheel
}