# Domain-specific GraphQL types


"""Convertible roof."""
type Convertible @vspec(element: BRANCH, fqn: "Vehicle.Cabin.Convertible") {
  """Roof status on convertible vehicles."""
  status: Vehicle_Cabin_Convertible_Status_Enum @vspec(element: SENSOR, fqn: "Vehicle.Cabin.Convertible.Status")
}

"""Allowed values for Vehicle.Cabin.Convertible.Status."""
enum Vehicle_Cabin_Convertible_Status_Enum @vspec(element: SENSOR, fqn: "Vehicle.Cabin.Convertible.Status", metadata: [{key: "allowed", value: "['UNDEFINED', 'CLOSED', 'OPEN', 'CLOSING', 'OPENING', 'STALLED']"}]) {
  UNDEFINED
  CLOSED
  OPEN
  CLOSING
  OPENING
  STALLED
}