# Domain-specific GraphQL types

"""
Signals related to Diesel Exhaust Fluid (DEF). DEF is called AUS32 in ISO 22241.
"""
type DieselExhaustFluid
  @vspec(element: BRANCH, fqn: "Vehicle.Powertrain.CombustionEngine.DieselExhaustFluid") {
  """
  Capacity in liters of the Diesel Exhaust Fluid Tank.
  """
  capacity(unit: VolumeUnitEnum = LITER): Float
    @vspec(
      element: ATTRIBUTE
      fqn: "Vehicle.Powertrain.CombustionEngine.DieselExhaustFluid.Capacity"
    )

  """
  Indicates if the Diesel Exhaust Fluid level is low. True if level is low. Definition of low is vehicle dependent.
  """
  isLevelLow: Boolean
    @vspec(
      element: SENSOR
      fqn: "Vehicle.Powertrain.CombustionEngine.DieselExhaustFluid.IsLevelLow"
    )

  """
  Level of the Diesel Exhaust Fluid tank as percent of capacity. 0 = empty. 100 = full.
  """
  level(unit: RelationUnitEnum = PERCENT): UInt8
    @vspec(element: SENSOR, fqn: "Vehicle.Powertrain.CombustionEngine.DieselExhaustFluid.Level")
    @range(min: 0, max: 100)

  """
  Remaining range in meters of the Diesel Exhaust Fluid present in the vehicle.
  """
  range(unit: LengthUnitEnum = METER): UInt32
    @vspec(element: SENSOR, fqn: "Vehicle.Powertrain.CombustionEngine.DieselExhaustFluid.Range")
}
