# Domain-specific GraphQL types

"""
License plate lights.
"""
type LicensePlate @vspec(element: BRANCH, fqn: "Vehicle.Body.Lights.LicensePlate") {
  """
  Indicates if light is defect. True = Light is defect. False = Light has no defect.
  """
  isDefect: Boolean @vspec(element: SENSOR, fqn: "Vehicle.Body.Lights.LicensePlate.IsDefect")

  """
  Indicates if light is on or off. True = On. False = Off.
  """
  isOn: Boolean @vspec(element: ACTUATOR, fqn: "Vehicle.Body.Lights.LicensePlate.IsOn")
}
