# Domain-specific GraphQL types


"""All mirrors."""
type Mirrors @vspec(element: BRANCH, fqn: "Vehicle.Body.Mirrors") {

  """
  Is mirror folded? True = Fully or partially folded. False = Fully unfolded.
  """
  isFolded: Boolean @vspec(element: ACTUATOR, fqn: "Vehicle.Body.Mirrors.IsFolded")

  """Mirror Heater on or off. True = Heater On. False = Heater Off."""
  isHeatingOn: Boolean @vspec(element: ACTUATOR, fqn: "Vehicle.Body.Mirrors.IsHeatingOn")

  """
  Is mirror movement locked? True = Locked, mirror will not react to Tilt/Pan change. False = Unlocked.
  """
  isLocked: Boolean @vspec(element: ACTUATOR, fqn: "Vehicle.Body.Mirrors.IsLocked")

  """
  Mirror pan as a percent. 0 = Center Position. 100 = Fully Left Position. -100 = Fully Right Position.
  """
  pan(unit: RelationUnitEnum = PERCENT): Int8 @vspec(element: ACTUATOR, fqn: "Vehicle.Body.Mirrors.Pan")
    @deprecated(reason: "v6.0 Replaced with Yaw - Note that direction changes!")
    @range(min: -100, max: 100)

  """
  Mirror tilt as a percent. 0 = Center Position. 100 = Fully Upward Position. -100 = Fully Downward Position.
  """
  tilt(unit: RelationUnitEnum = PERCENT): Int8 @vspec(element: ACTUATOR, fqn: "Vehicle.Body.Mirrors.Tilt")
    @range(min: -100, max: 100)

  """
  Relative mirror yaw angle, measured from the vehicle sprung mass X-axis as defined by ISO 23150:2023 to the mirror X-axis, around the vehicle Z-axis (right-hand rule). 0 = Mirror in default position. Exact position (yaw relative to vehicle X-axis) is vehicle dependent. 100 = Maximum yaw. Mirror rotated clockwise as much as possible around Z-axis. -100 = Minimum yaw. Mirror rotated counter-clockwise as much as possible around Z-axis.
    @range(min: -100, max: 100)
  """
  yaw(unit: RelationUnitEnum = PERCENT): Int8 @vspec(element: ACTUATOR, fqn: "Vehicle.Body.Mirrors.Yaw")
}