# Domain-specific GraphQL types

"""
Describes signals related to the seat bottom of the seat.
"""
type Seating @vspec(element: BRANCH, fqn: "Vehicle.Cabin.Seat.Seating") {
  """
  Heating or Cooling requsted for the Item. -100 = Maximum cooling, 0 = Heating/cooling deactivated, 100 = Maximum heating.
  """
  heatingCooling(unit: RelationUnitEnum = PERCENT): Int8
    @vspec(element: ACTUATOR, fqn: "Vehicle.Cabin.Seat.HeatingCooling")
    @range(min: -100, max: 100)

  """
  Is switch to decrease seating length engaged.
  """
  isBackwardSwitchEngaged: Boolean
    @vspec(element: ACTUATOR, fqn: "Vehicle.Cabin.Seat.IsBackwardSwitchEngaged")

  """
  Is switch to increase seating length engaged.
  """
  isForwardSwitchEngaged: Boolean
    @vspec(element: ACTUATOR, fqn: "Vehicle.Cabin.Seat.IsForwardSwitchEngaged")

  """
  Length adjustment of seating. 0 = Adjustable part of seating in rearmost position (Shortest length of seating).
  """
  length(unit: LengthUnitEnum = MILLIMETER): UInt16
    @vspec(element: ACTUATOR, fqn: "Vehicle.Cabin.Seat.Seating.Length")
    @range(min: 0)

  """
  Seat bottom side bolster support left. 0 = Minimum support (widest side bolster setting). 100 = Maximum support.
  """
  sideBolsterSupportLeft(unit: RelationUnitEnum = PERCENT): Float
    @vspec(element: ACTUATOR, fqn: "Vehicle.Cabin.Seat.Seating.SideBolsterSupportLeft")
    @range(min: 0, max: 100)

  """
  Seat bottom side bolster support right. 0 = Minimum support (widest side bolster setting). 100 = Maximum support.
  """
  sideBolsterSupportRight(unit: RelationUnitEnum = PERCENT): Float
    @vspec(element: ACTUATOR, fqn: "Vehicle.Cabin.Seat.Seating.SideBolsterSupportRight")
    @range(min: 0, max: 100)
}
