# Domain-specific GraphQL types


"""Brake signals for wheel"""
type Wheel_Brake @vspec(element: BRANCH, fqn: "Vehicle.Chassis.Axle.Wheel.Brake") {
  """Brake fluid level as percent. 0 = Empty. 100 = Full."""
  fluidLevel(unit: RelationUnitEnum = PERCENT): UInt8 @vspec(element: SENSOR, fqn: "Vehicle.Chassis.Axle.Wheel.Brake.FluidLevel")
    @range(max: 100)

  """Brake pad wear status. True = Worn. False = Not Worn."""
  isBrakesWorn: Boolean @vspec(element: SENSOR, fqn: "Vehicle.Chassis.Axle.Wheel.Brake.IsBrakesWorn")

  """
  Brake fluid level status. True = Brake fluid level low. False = Brake fluid level OK.
  """
  isFluidLevelLow: Boolean @vspec(element: SENSOR, fqn: "Vehicle.Chassis.Axle.Wheel.Brake.IsFluidLevelLow")

  """Brake pad wear as percent. 0 = No Wear. 100 = Worn."""
  padWear(unit: RelationUnitEnum = PERCENT): UInt8 @vspec(element: SENSOR, fqn: "Vehicle.Chassis.Axle.Wheel.Brake.PadWear")
    @range(max: 100)
}